language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  # optional
  - 2.3.0-preview1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2

env:
  - INTEGRATION=openldap

install:
  - if [ "$INTEGRATION" = "openldap" ]; then sudo script/install-openldap; fi
  - bundle install

script: bundle exec rake ci

matrix:
  allow_failures:
    - rvm: 2.3.0-preview1
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: rbx-2
  fast_finish: true

notifications:
  email: false
